base_url: "https://cloudiotdevice.googleapis.com/v1"

project_id: "xxxxxxxx"
cloud_region: "xxxx
registry_id: "Reg_xxxxx"
service_account_json: "xxxx.json"

algorithm: "RS256"
path: "CA/"
ca_certs: "https://pki.google.com/roots.pem"
private_key_file: GCP_rsa_private.pem
public_key_file: GCP_rsa_public.pem

message_type: "event"

topic_new: "new"