
Connection: AWS

sample : 5

Sense_HAT:
    humidity:
      active: ok
      msg: humidity
      max: 100
      min: 0
    temperature:
      active: ok
      msg: temperature
      max: 60
      min: 0
    pressure:
      active: ok
      msg: pressure
      max: 1500
      min: 0
    acceleration:
      active: ok
      msg: accel
      max: 60
      min: 0

      