# List of connection settings
connection:
  cloud: AWS
  things: "MyRaspberryPi"
  broker: "xxxxxxxxxxxx-ats.iot.xx-xxxx-x.amazonaws.com"
  port: 8883
  Certificate:
    path: "CA/"
    ca: "AmazonRootCA1.pem"
    certificate: "xxxxxxxxxx-certificate.pem.crt"
    private_key: "xxxxxxxxxx-private.pem.key"
  topic:
    update: "$aws/things/MyRaspberryPi/shadow/update"
    delta: "$aws/things/MyRaspberryPi/shadow/update/delta"
    accepted: "$aws/things/MyRaspberryPi/shadow/update/accepted"
    rejected: "$aws/things/MyRaspberryPi/shadow/update/rejected"

   